name: Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
      - '.vscode/**'
      - '.gitignore'
      - '.editorconfig'
      - 'LICENSE.md'
      - '**/*/README.md'
      - '**/*/Dockerfile'
      - 'scripts/**'
jobs:
  build:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Create version tag
        id: version
        run: echo "version=$(date +%Y.%m.%d.%H%M%S)" >> $GITHUB_OUTPUT
      - name: Build and push image
        working-directory: src/API
        run: |
          TAG=${{ secrets.DOCKERHUB_USERNAME }}/restapiplayground.stevanfreeborn.com:${{ steps.version.outputs.version }}
          docker build -t $TAG .
          docker push $TAG
  deploy:
    name: Deploy to server
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Run image on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker stop restapiplayground.stevanfreeborn.com
            docker rm restapiplayground.stevanfreeborn.com
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/restapiplayground.stevanfreeborn.com:${{ needs.build.outputs.version }}
            docker run --restart always -d -p 7777:8080 --name restapiplayground.stevanfreeborn.com ${{ secrets.DOCKERHUB_USERNAME }}/restapiplayground.stevanfreeborn.com:${{ needs.build.outputs.version }}
